function [fitresult, gof] = createFit_power(x_array, y_array,fitmethod)
%CREATEFIT1(X_ARRAY,Y_ARRAY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x_array
%      Y Output: y_array
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Jun-2017 16:48:38


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( y_array, x_array );
if (fitmethod==1)
    % Set up fittype and options.
    ft = fittype('poly9');
    opts = fitoptions( 'Method', 'LinearLeastSquares' );
    opts.Robust = 'off';
    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );
else if (fitmethod== 2)
        % Set up fittype and options.
        ft = fittype('exp2');
        opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
        opts.Display = 'Off';
        opts.Normalize = 'off';
        opts.Robust= 'off';
        opts.StartPoint = [484.671459315234 0.000696220878936856 -15444.4869929294 -0.01007974240935];
        
        % Fit model to data.
        [fitresult, gof] = fit( xData, yData, ft, opts );
    end
end
%grid on


